# Generated by Django 5.2 on 2025-05-18 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mission", models.TextField()),
                ("history", models.TextField()),
            ],
            options={
                "verbose_name": "About Page Content",
                "verbose_name_plural": "About Page Content",
            },
        ),
        migrations.CreateModel(
            name="BannerImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Image title for administrative purposes",
                        max_length=100,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Image will be resized to fit banner height",
                        upload_to="banner/",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Optional brief description of the image",
                        max_length=200,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order in which the image will be displayed",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this image is displayed in the banner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Banner Image",
                "verbose_name_plural": "Banner Images",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="HomeContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headline", models.CharField(max_length=200)),
                ("subheadline", models.TextField()),
                (
                    "markdown_content",
                    models.TextField(
                        blank=True,
                        help_text="Markdown content for the home page main section",
                    ),
                ),
                (
                    "youtube_video_url",
                    models.URLField(
                        blank=True,
                        help_text="YouTube video embed URL for the home page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Home Page Content",
                "verbose_name_plural": "Home Page Content",
            },
        ),
        migrations.CreateModel(
            name="LabInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department", models.CharField(max_length=200)),
                ("building", models.CharField(max_length=200)),
                ("room", models.CharField(max_length=50)),
                ("institution", models.CharField(max_length=200)),
                ("address", models.TextField()),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("map_embed_url", models.URLField(help_text="Google Maps embed URL")),
            ],
            options={
                "verbose_name": "Lab Information",
                "verbose_name_plural": "Lab Information",
            },
        ),
        migrations.CreateModel(
            name="ResearchLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="research_lines/"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("slug", models.SlugField(blank=True, max_length=250, unique=True)),
            ],
            options={
                "verbose_name": "Research Line",
                "verbose_name_plural": "Research Lines",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SocialMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "github",
                    models.URLField(blank=True, help_text="GitHub repository URL"),
                ),
                (
                    "youtube",
                    models.URLField(blank=True, help_text="YouTube channel URL"),
                ),
            ],
            options={
                "verbose_name": "Social Media Links",
                "verbose_name_plural": "Social Media Links",
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=100)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("PI", "Principal Investigator"),
                            ("POSTDOC", "Postdoctoral Researcher"),
                            ("PHD", "PhD Student"),
                            ("MS", "Master Student"),
                            ("UNDERGRAD", "Undergraduate Student"),
                            ("STAFF", "Staff"),
                            ("ALUMNI", "Alumni"),
                        ],
                        max_length=20,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("github", models.URLField(blank=True)),
                ("linkedin", models.URLField(blank=True)),
                ("personal_website", models.URLField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="members/"),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Team Member",
                "verbose_name_plural": "Team Members",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ResearchProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="projects/"),
                ),
                ("featured", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                ("slug", models.SlugField(blank=True, max_length=250, unique=True)),
                (
                    "content",
                    models.TextField(
                        blank=True, help_text="Detailed content for project detail page"
                    ),
                ),
                (
                    "research_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects",
                        to="core.researchline",
                    ),
                ),
            ],
            options={
                "verbose_name": "Research Project",
                "verbose_name_plural": "Research Projects",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("authors", models.CharField(max_length=500)),
                ("venue", models.CharField(max_length=200)),
                ("year", models.CharField(max_length=4)),
                ("doi", models.CharField(blank=True, max_length=100)),
                ("link", models.URLField(blank=True)),
                ("abstract", models.TextField(blank=True)),
                ("highlighted", models.BooleanField(default=False)),
                (
                    "authors_from_team",
                    models.ManyToManyField(
                        blank=True, related_name="publications", to="core.teammember"
                    ),
                ),
            ],
            options={
                "verbose_name": "Publication",
                "verbose_name_plural": "Publications",
                "ordering": ["-year", "title"],
            },
        ),
    ]
