# Generated by Django 5.2 on 2025-04-23 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mission", models.TextField()),
                ("history", models.TextField()),
            ],
            options={
                "verbose_name": "About Page Content",
                "verbose_name_plural": "About Page Content",
            },
        ),
        migrations.CreateModel(
            name="Collaborator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("institution", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("website", models.URLField(blank=True)),
            ],
            options={
                "verbose_name": "Collaborator",
                "verbose_name_plural": "Collaborators",
            },
        ),
        migrations.CreateModel(
            name="FundingSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("website", models.URLField(blank=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="funding/"),
                ),
            ],
            options={
                "verbose_name": "Funding Source",
                "verbose_name_plural": "Funding Sources",
            },
        ),
        migrations.CreateModel(
            name="HomeContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headline", models.CharField(max_length=200)),
                ("subheadline", models.TextField()),
                ("mission_statement", models.TextField()),
            ],
            options={
                "verbose_name": "Home Page Content",
                "verbose_name_plural": "Home Page Content",
            },
        ),
        migrations.CreateModel(
            name="LabInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department", models.CharField(max_length=200)),
                ("building", models.CharField(max_length=200)),
                ("room", models.CharField(max_length=50)),
                ("institution", models.CharField(max_length=200)),
                ("address", models.TextField()),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("map_embed_url", models.URLField(help_text="Google Maps embed URL")),
            ],
            options={
                "verbose_name": "Lab Information",
                "verbose_name_plural": "Lab Information",
            },
        ),
        migrations.CreateModel(
            name="ResearchArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Research Area",
                "verbose_name_plural": "Research Areas",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=100)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("PI", "Principal Investigator"),
                            ("POSTDOC", "Postdoctoral Researcher"),
                            ("PHD", "PhD Student"),
                            ("MS", "Master Student"),
                            ("UNDERGRAD", "Undergraduate Student"),
                            ("STAFF", "Staff"),
                            ("ALUMNI", "Alumni"),
                        ],
                        max_length=20,
                    ),
                ),
                ("bio", models.TextField()),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("personal_website", models.URLField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="members/"),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Team Member",
                "verbose_name_plural": "Team Members",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ResearchProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="projects/"),
                ),
                ("featured", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Research Project",
                "verbose_name_plural": "Research Projects",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("authors", models.CharField(max_length=500)),
                ("venue", models.CharField(max_length=200)),
                ("year", models.CharField(max_length=4)),
                ("doi", models.CharField(blank=True, max_length=100)),
                ("link", models.URLField(blank=True)),
                ("abstract", models.TextField(blank=True)),
                ("highlighted", models.BooleanField(default=False)),
                (
                    "authors_from_team",
                    models.ManyToManyField(
                        blank=True, related_name="publications", to="core.teammember"
                    ),
                ),
            ],
            options={
                "verbose_name": "Publication",
                "verbose_name_plural": "Publications",
                "ordering": ["-year", "title"],
            },
        ),
    ]
