# Generated by Django 5.2 on 2025-04-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="researchproject",
            name="content",
            field=models.TextField(
                blank=True, help_text="Detailed content for project detail page"
            ),
        ),
        migrations.AddField(
            model_name="researchproject",
            name="slug",
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]
