# Generated by Django 5.2 on 2025-04-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_researchproject_content_researchproject_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="BannerImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Image title for administrative purposes",
                        max_length=100,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Image will be resized to fit banner height",
                        upload_to="banner/",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Optional brief description of the image",
                        max_length=200,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order in which the image will be displayed",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this image is displayed in the banner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Banner Image",
                "verbose_name_plural": "Banner Images",
                "ordering": ["order"],
            },
        ),
    ]
