# Generated by Django 5.2 on 2025-05-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_delete_aboutcontent"),
    ]

    operations = [
        migrations.AddField(
            model_name="homecontent",
            name="section_image",
            field=models.ImageField(
                blank=True,
                help_text="Image for the second home page section",
                null=True,
                upload_to="home_sections/",
            ),
        ),
        migrations.AddField(
            model_name="homecontent",
            name="section_markdown_content",
            field=models.TextField(
                blank=True,
                help_text="Markdown content for the second home page section",
            ),
        ),
    ]
