# Generated by Django 5.2 on 2025-05-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_homecontent_section_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homecontent",
            name="subheadline",
            field=models.CharField(max_length=200),
        ),
    ]
