# Generated by Django 5.2 on 2025-04-24 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_bannerimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResearchLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="research_lines/"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("slug", models.SlugField(blank=True, max_length=250, unique=True)),
                (
                    "research_area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="research_lines",
                        to="core.researcharea",
                    ),
                ),
            ],
            options={
                "verbose_name": "Research Line",
                "verbose_name_plural": "Research Lines",
                "ordering": ["order"],
            },
        ),
        migrations.DeleteModel(
            name="Collaborator",
        ),
        migrations.DeleteModel(
            name="FundingSource",
        ),
        migrations.AddField(
            model_name="researchproject",
            name="research_line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="core.researchline",
            ),
        ),
    ]
