# Generated by Django 5.2 on 2025-04-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_researchline_delete_collaborator_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teammember",
            name="bio",
        ),
        migrations.AddField(
            model_name="teammember",
            name="github",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="teammember",
            name="linkedin",
            field=models.URLField(blank=True),
        ),
    ]
