# Generated by Django 5.2 on 2025-05-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_researchline_banner_image_researchline_publications_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teammember",
            options={
                "ordering": ["last_name"],
                "verbose_name": "Team Member",
                "verbose_name_plural": "Team Members",
            },
        ),
        migrations.RenameField(
            model_name="teammember",
            old_name="name",
            new_name="first_name",
        ),
        migrations.RemoveField(
            model_name="teammember",
            name="active",
        ),
        migrations.RemoveField(
            model_name="teammember",
            name="order",
        ),
        migrations.RemoveField(
            model_name="teammember",
            name="title",
        ),
        migrations.AddField(
            model_name="teammember",
            name="alum",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="teammember",
            name="last_name",
            field=models.CharField(default="bruh", max_length=100),
            preserve_default=False,
        ),
    ]
