# Generated by Django 5.2 on 2025-04-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_teammember_bio_teammember_github_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "github",
                    models.URLField(blank=True, help_text="GitHub repository URL"),
                ),
                (
                    "youtube",
                    models.URLField(blank=True, help_text="YouTube channel URL"),
                ),
            ],
            options={
                "verbose_name": "Social Media Links",
                "verbose_name_plural": "Social Media Links",
            },
        ),
    ]
