# Generated by Django 5.2 on 2025-05-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_teammember_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammember",
            name="position",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
