# Generated by Django 5.2 on 2025-05-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_researchproject_banner_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="researchproject",
            name="research_line",
        ),
        migrations.AddField(
            model_name="researchproject",
            name="research_lines",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="core.researchline"
            ),
        ),
    ]
