# Generated by Django 5.2 on 2025-05-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_remove_researchproject_research_line_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="researchproject",
            name="research_lines",
        ),
        migrations.AddField(
            model_name="researchline",
            name="projects",
            field=models.ManyToManyField(
                blank=True, related_name="research_lines_set", to="core.researchproject"
            ),
        ),
    ]
