# Generated by Django 5.2 on 2025-05-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_remove_researchproject_research_lines_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="publication",
            options={
                "ordering": ["-date", "title"],
                "verbose_name": "Publication",
                "verbose_name_plural": "Publications",
            },
        ),
        migrations.RenameField(
            model_name="publication",
            old_name="link",
            new_name="paperlink",
        ),
        migrations.RemoveField(
            model_name="publication",
            name="doi",
        ),
        migrations.RemoveField(
            model_name="publication",
            name="venue",
        ),
        migrations.RemoveField(
            model_name="publication",
            name="year",
        ),
        migrations.AddField(
            model_name="publication",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="publication",
            name="pdflink",
            field=models.URLField(blank=True),
        ),
    ]
