# Generated by Django 5.2 on 2025-05-18 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_publication_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publication",
            name="authors_from_team",
        ),
        migrations.RemoveField(
            model_name="publication",
            name="highlighted",
        ),
    ]
