# Generated by Django 5.2 on 2025-05-18 19:30

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_publication_image"),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="bannerimage",
            name="image",
            field=filer.fields.image.FilerImageField(
                blank=True,
                help_text="Image will be resized to fit banner height",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="banner_images",
                to=settings.FILER_IMAGE_MODEL,
            ),
        ),
    ]
