# Generated by Django 5.2 on 2025-05-18 19:40

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_bannerimage_image"),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="homecontent",
            name="section_image",
            field=filer.fields.image.FilerImageField(
                blank=True,
                help_text="Image for the second home page section",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="home_section_images",
                to=settings.FILER_IMAGE_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="projectgalleryimage",
            name="image",
            field=filer.fields.image.FilerImageField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project_gallery",
                to=settings.FILER_IMAGE_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="image",
            field=filer.fields.image.FilerImageField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="publication_images",
                to=settings.FILER_IMAGE_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="researchline",
            name="banner_image",
            field=filer.fields.image.FilerImageField(
                blank=True,
                help_text="Banner image for the research line",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="research_line_banners",
                to=settings.FILER_IMAGE_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="researchline",
            name="image",
            field=filer.fields.image.FilerImageField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="research_line_images",
                to=settings.FILER_IMAGE_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="researchlinegalleryimage",
            name="image",
            field=filer.fields.image.FilerImageField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="research_line_gallery",
                to=settings.FILER_IMAGE_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="researchproject",
            name="banner_image",
            field=filer.fields.image.FilerImageField(
                blank=True,
                help_text="Banner image for the project",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project_banners",
                to=settings.FILER_IMAGE_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="researchproject",
            name="image",
            field=filer.fields.image.FilerImageField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project_images",
                to=settings.FILER_IMAGE_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="image",
            field=filer.fields.image.FilerImageField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="member_images",
                to=settings.FILER_IMAGE_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="BannerImage",
        ),
    ]
