# Generated by Django 5.2 on 2025-05-18 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_alter_homecontent_section_image_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="homecontent",
            old_name="markdown_content",
            new_name="about_markdown_content",
        ),
    ]
