# Generated by Django 5.2 on 2025-05-18 20:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_rename_markdown_content_homecontent_about_markdown_content"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="researchline",
            options={
                "ordering": ["-date"],
                "verbose_name": "Research Line",
                "verbose_name_plural": "Research Lines",
            },
        ),
        migrations.AlterModelOptions(
            name="researchproject",
            options={
                "ordering": ["-date"],
                "verbose_name": "Research Project",
                "verbose_name_plural": "Research Projects",
            },
        ),
        migrations.RemoveField(
            model_name="researchline",
            name="order",
        ),
        migrations.RemoveField(
            model_name="researchproject",
            name="featured",
        ),
        migrations.RemoveField(
            model_name="researchproject",
            name="order",
        ),
        migrations.RemoveField(
            model_name="teammember",
            name="role",
        ),
        migrations.AddField(
            model_name="researchline",
            name="date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="researchproject",
            name="date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teammember",
            name="principal_investigator",
            field=models.BooleanField(default=False),
        ),
    ]
