# Generated by Django 5.2 on 2025-05-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_researchline_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="researchline",
            name="video_url",
            field=models.URLField(
                blank=True, help_text="YouTube video embed URL for the research line"
            ),
        ),
        migrations.AddField(
            model_name="researchproject",
            name="video_url",
            field=models.URLField(
                blank=True, help_text="YouTube video embed URL for the project"
            ),
        ),
    ]
