# Generated by Django 5.2 on 2025-05-18 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_researchline_video_url_researchproject_video_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="researchline",
            name="image",
        ),
        migrations.RemoveField(
            model_name="researchproject",
            name="image",
        ),
    ]
