# Generated by Django 5.2 on 2025-05-19 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_remove_researchline_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "position",
                    models.CharField(help_text="Position title/type", max_length=200),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        help_text="Contact email for applications", max_length=254
                    ),
                ),
                ("date_posted", models.DateField(auto_now_add=True)),
                (
                    "application_deadline",
                    models.DateField(help_text="Application deadline"),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed description of the position"),
                ),
                (
                    "requirements",
                    models.TextField(help_text="Requirements for the position"),
                ),
                (
                    "instructions",
                    models.TextField(blank=True, help_text="Application instructions"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about the position"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this position is currently open",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Position",
                "verbose_name_plural": "Job Positions",
                "ordering": ["-date_posted"],
            },
        ),
    ]
