# Generated by Django 5.2 on 2025-05-19 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_jobposition"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jobposition",
            options={
                "verbose_name": "Job Position",
                "verbose_name_plural": "Job Positions",
            },
        ),
        migrations.RemoveField(
            model_name="jobposition",
            name="date_posted",
        ),
        migrations.RemoveField(
            model_name="jobposition",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="jobposition",
            name="position",
        ),
        migrations.AlterField(
            model_name="jobposition",
            name="application_deadline",
            field=models.TextField(help_text="Application deadline"),
        ),
    ]
