# Generated by Django 5.2 on 2025-05-25 21:22

import prose.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_remove_researchproject_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="researchline",
            name="content",
            field=prose.fields.RichTextField(
                blank=True,
                help_text="Rich text content with images for the research line",
            ),
        ),
        migrations.AddField(
            model_name="researchproject",
            name="content",
            field=prose.fields.RichTextField(
                blank=True, help_text="Rich text content with images for the project"
            ),
        ),
    ]
