# Generated by Django 5.2 on 2025-05-25 23:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_researchline_content_researchproject_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="researchline",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="researchproject",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
