# Generated by Django 5.2 on 2025-05-25 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_alter_researchline_date_alter_researchproject_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="researchline",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="researchproject",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
