# Generated by Django 5.2 on 2026-05-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_researchline_active_researchproject_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="codelink",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="publication",
            name="websitelink",
            field=models.URLField(blank=True),
        ),
    ]
