# Generated by Django 5.2 on 2026-08-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_publication_codelink_publication_websitelink"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammember",
            name="alum_destination",
            field=models.CharField(
                blank=True,
                help_text="Where this person went after the lab, e.g. 'Google DeepMind' or 'PhD student at MIT'. Only shown for alumni.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="teammember",
            name="alum_destination_link",
            field=models.URLField(
                blank=True,
                help_text="Optional link for the destination above (lab, company, or personal page).",
            ),
        ),
    ]
